Repository shelcia/Bloggram, pull requests merged in 2023-12, with the labels that each got.

#481 Added Name , Password validation and password visibility toggle Icon."
  src/pages/auth/Signup.jsx
Labels: codepeak, medium

#491 Added Password Viewer Button On Login Page
  src/pages/auth/Login.jsx
Labels: codepeak, easy

#496 404 page is done
  src/pages/others/ErrorPage.css
  src/pages/others/ErrorPage.jsx
  src/routes.jsx
Labels: codepeak, easy

#500 fixed bug by modifying handleChange function issue #451
  src/pages/dashboard/blog/AddBlog.jsx
Labels: codepeak

#499 Added files for the new logo
  public/bloggram-new.ico
  public/bloggram-new.png
Labels: codepeak, hard

#506 added a boolean hasBlogContent
  src/pages/dashboard/components/BlogSections.jsx
Labels: codepeak, easy
